### ISSUE TITLE
When i run test.py i get this error what should i do??? thanks in advance

### ISSUE THREAD

**Issue by ajithnaruto** [shagunsodhani/Image-Caption-Generator#1]
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    mode="debug")
  File "test.py", line 84, in predict
    model.load_weights(data_dir + "model/" + weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2613, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/ajith/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ajith/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-nCYoKW-build/h5py/h5f.c:2117)
IOError: Unable to open file (Unable to open file: name = '/home/ajith/image-caption-generator/data/model/weights-00.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by shagunsodhani** [comment]
Hey @ajithnaruto `test.py` is not a file to test the software (in the traditional sense). It is to test the performance of the trained model. So you should be training the model first. Do let me know if this helps.

**Comment by shagunsodhani** [comment]
Hey @ajithnaruto I assume that your problem was resolved. Feel free to re-open this issue if it hasnt been fixed.
